INSERT INTO tbbiere VALUES

('Ambrasse-Temps', '5.5', 'Ambrée', ''),
('Blanche de Bruges', '4.8', 'Blanche', ''),
('Blanche de Hoegaarden', '4.9', 'Blanche', ''),
('Blanche de Namur à la Pomme', '3.2', 'Fruitée', ''),
('Blanche Neuve', '4.5', 'Blanche', ''),
('Bourgogne Des Flandres', '5.0', 'Spéciale Brune', ''),
('Bush Ambrée', '12.0', 'Spéciale Ambrée', ''),
('Bush Ambrée Triple', '12.0', 'Spéciale Ambrée', ''),
('Bush de Noël', '12.0', 'Spéciale Noël', ''),
('Bush Blonde', '10.5', 'Spéciale Blonde', ''),
('Carolus Hopsinjoor', '8.0', 'Spéciale Blonde', ''),
('Chimay Blanche', '8.0', 'Trappiste', ''),
('Chimay Bleue', '9.0', 'Trappiste', ''),
('Chimay Rouge', '7.0', 'Trappiste', ''),
('Chouffe', '8.0', 'Spéciale Blonde', ''),
('Cubanisto', '5.9', 'Rhum', ''),
('Cuvée des Trolls', '7.0', 'Spéciale Blonde', ''),
('Duvel', '8.5', 'Spéciale Blonde', ''),
('Duvel Triple Hop', '9.5', 'Spéciale Blonde', ''),
('Ginette', '5.0', 'Spéciale Blonde', ''),
('Grimbergen Blonde', '6.7', 'Abbaye', ''),
('Grimbergen Brune', '6.5', 'Spéciale Brune', ''),
('Hoegaarden Radler Agrum', '2.0', 'Spéciale Ambrée', ''),
('Houppe', '7.0', 'Spéciale Blonde', ''),
('Julius', '8.8', 'Spéciale Blonde', ''),
('Jupiler','5.2','Pils', ''),
('Kasteel Rouge', '8.0', 'Fruitée', ''),
('Kriek Bellevue', '5.2', 'Fruitée', ''),
('Kriek Max', '3.2', 'Fruitée', ''),
('Kriek Mort Subite', '4.5', 'Fruitée', ''),
('La Trappe Blonde', '6.5', 'Spéciale Blonde', ''),
('Leffe Blonde', '6.5', 'Abbaye', ''),
('Leffe Brune', '6.5', 'Abbaye', ''),
('Leffe Royale', '7.5', 'Spéciale Ambrée', ''),
('Leffe Royale Cascade Ipa', '7.5', 'Abbaye', ''),
('Leffe Ruby', '5.0', 'Fruitée', ''),
('Lindermans Kriek', '4.0', 'Fruitée', ''),
('Maes', '4.9', 'Pils', ''),
('Mystic Cerise', '3.5', 'Fruitée', ''),
('Mystic White', '5.1', 'Blanche', ''),
('Omer', '8.0', 'Spéciale Blonde', ''),
('Orval', '6.2', 'Trappiste', ''),
('Pêche Mel Bush', '8.5', 'Fruitée', ''),
('Primus', '5.2', 'pils', ''),
('Rochefort 8', '9.2', 'Trappiste', ''),
('Rochefort 10', '11.3', 'Trappiste', ''),
('Sainte Nitouche', '6.0', 'Spéciale Blonde', ''),
('Stella Artois', '5.2', 'Pils', ''),
('Surfine', '6.5', 'Saisons', ''),
('Temps des Brunes', '6.0', 'Spéciale Brune', ''),
('Timmermans Pêche', '5.0', 'Fruitée', ''),
('Troubadour Magma', '9.0', 'Spéciale Ambrée', ''),
('Triple Karmeliet', '8.0', 'Spéciale Blonde', ''),
('Vedett', '6.0', 'Pils', ''),
('Vedett Ipa', '6.0', 'IPA', ''),
('Westmalle Triple', '9.5', 'Trappiste', '');






