INSERT INTO tbcarte VALUES

('Jupiler' , 'Barger'),
('Leffe Blonde', 'Barger'),
('Triple Karmeliet', 'Barger'),
('Chouffe', 'Barger'),
('Vedett', 'Barger'),
('Bush Blonde', 'Barger'),
('Chimay Bleue', 'Barger'),
('Rochefort 10', 'Barger'),
('Westmalle Triple', 'Barger'),
('Orval', 'Barger'),

('Primus', 'Beer Bar'),
('Mystic White', 'Beer Bar'),
('Chouffe', 'Beer Bar'),
('Mystic Cerise', 'Beer Bar'),
('Grimbergen Brune', 'Beer Bar'),
('Omer Blonde', 'Beer Bar'),
('Sainte Nitouche', 'Beer Bar'),
('Bourgogne Des Flandres', 'Beer Bar'),
('Duvel', 'Beer Bar'),
('Vedett', 'Beer Bar'),

('Surfine', 'Brasse-Temps'),
('Bush Blonde', 'Brasse-Temps'),
('Bush Ambrée', 'Brasse-Temps'),
('Bush de Noël', 'Brasse-Temps'),
('Pêche Mel Bush', 'Brasse-Temps'),
('Cuvée des Trolls', 'Brasse-Temps'),
('Bush Ambrée Triple', 'Brasse-Temps'),
('Blanche Neuve', 'Brasse-Temps'),
('Temps des Brunes', 'Brasse-Temps'),
('Ambrasse-Temps', 'Brasse-Temps'),

('Jupiler', 'Cambridge'),
('Blanche de Hoegaarden', 'Cambridge'),
('Kriek Mort Subite', 'Cambridge'),
('Leffe Blonde', 'Cambridge'),
('La Trappe Blonde', 'Cambridge'),
('Chimay Rouge', 'Cambridge'),
('Chimay Bleue', 'Cambridge'),
('Orval', 'Cambridge'),
('Rochefort 8', 'Cambridge'),
('Westmalle Triple', 'Cambridge'),

('Timmermans Pêche', 'Galoute'),
('Kriek Max', 'Galoute'),
('Pêche Mel Bush', 'Galoute'),
('Leffe Ruby', 'Galoute'),
('Hoegaarden Radler Agrum', 'Galoute'),
('Kasteel Rouge', 'Galoute'),
('Blanche de Namur à la Pomme', 'Galoute'),
('Lupulus', 'Galoute'),
('Houppe', 'Galoute'),
('Cubanisto', 'Galoute'),

('Stella Artois','Knokke Out University'),
('Kriek Bellevue','Knokke Out University'),
('Lindermans Kriek','Knokke Out University'),
('Leffe Brune','Knokke Out University'),
('Leffe Ruby','Knokke Out University'),
('Leffe Royale','Knokke Out University'),
('Julius','Knokke Out University'),
('Chimay Blanche','Knokke Out University'),
('Chimay Bleue','Knokke Out University'),
('Triple Karmeliet','Knokke Out University'),

('Stella Artois','Onlywood'),
('Blanche de Hoegaarden','Onlywood'),
('Triple Karmeliet','Onlywood'),
('Ginette','Onlywood'),
('Leffe Royale Cascade Ipa','Onlywood'),
('Houppe','Onlywood'),
('Duvel Triple Hop','Onlywood'),
('Vedett Ipa','Onlywood'),
('Carolus Hopsinjoor','Onlywood'),
('Troubadour Magma','Onlywood'),

('Maes','Rabelais'),
('Blanche de Bruges','Rabelais'),
('Grimbergen Blonde','Rabelais'),
('Kriek Mort Subite','Rabelais'),
('La Trappe Blonde','Rabelais'),
('Chimay Rouge','Rabelais'),
('Chimay Bleue','Rabelais'),
('Chimay Blanche','Rabelais'),
('Orval','Rabelais'),
('Rochefort 8','Rabelais');



