ALTER TABLE TbBiere auto_increment = 1;

INSERT INTO TbBiere(nombiere, alcoolemie, typebiere, image) VALUES

('Ambrasse-Temps', '5.5', 'Ambree', 'beers\\AmbrasseTemps.PNG'),
('Blanche de Bruges', '4.8', 'Blanche', 'beers\\BlancheDeBruges.PNG'),
('Blanche de Hoegaarden', '4.9', 'Blanche', 'beers\\BlancheDeHoegaarden.PNG'),
('Blanche de Namur à la Pomme', '3.2', 'Fruitee', 'beers\\BlancheDeNamurALaPomme.PNG'),
('Blanche Neuve', '4.5', 'Blanche', 'beers\\BlancheNeuve.PNG'),
('Bourgogne Des Flandres', '5.0', 'Speciale Brune', 'beers\\BourgogneDesFlandres.PNG'),
('Bush Ambree', '12.0', 'Speciale Ambree', 'beers\\BushAmbree.PNG'),
('Bush Ambree Triple', '12.0', 'Speciale Ambree', 'beers\\BushAmbreeTriple.PNG'),
('Bush de Noel', '12.0', 'Speciale Noel', 'beers\\BushDeNoel.PNG'),
('Bush Blonde', '10.5', 'Speciale Blonde', 'beers\\BushBlonde.PNG'),
('Carolus Hopsinjoor', '8.0', 'Speciale Blonde', 'beers\\CarolusHopsinjoor.PNG'),
('Chimay Blanche', '8.0', 'Trappiste', 'beers\\ChimayBlanche.PNG'),
('Chimay Bleue', '9.0', 'Trappiste', 'beers\\ChimayBleue.PNG'),
('Chimay Rouge', '7.0', 'Trappiste', 'beers\\ChimayRouge.PNG'),
('Chouffe', '8.0', 'Speciale Blonde', 'beers\\Chouffe.PNG'),
('Cubanisto', '5.9', 'Rhum', 'beers\\Cubanisto.PNG'),
('Cuvee des Trolls', '7.0', 'Speciale Blonde', 'beers\\CuveeDesTrolls.PNG'),
('Duvel', '8.5', 'Speciale Blonde', 'beers\\Duvel.PNG'),
('Duvel Triple Hop', '9.5', 'Speciale Blonde', 'beers\\DuvelTripleHop.PNG'),
('Ginette', '5.0', 'Speciale Blonde', 'beers\\Ginette.PNG'),
('Grimbergen Blonde', '6.7', 'Abbaye', 'beers\\GrimbergenBlonde.PNG'),
('Grimbergen Brune', '6.5', 'Speciale Brune', 'beers\\GrimbergenBrune.PNG'),
('Hoegaarden Radler Agrum', '2.0', 'Speciale Ambree', 'beers\\HoegaardenRadlerAgrum.PNG'),
('Houppe', '7.0', 'Speciale Blonde', 'beers\\Houppe.PNG'),
('Julius', '8.8', 'Speciale Blonde', 'beers\\Julius.PNG'),
('Jupiler','5.2','Pils', 'beers\\Jupiler.PNG'),
('Kasteel Rouge', '8.0', 'Fruitee', 'beers\\KasteelRouge.PNG'),
('Kriek Bellevue', '5.2', 'Fruitee', 'beers\\KriekBellevue.PNG'),
('Kriek Max', '3.2', 'Fruitee', 'beers\\KriekMax.PNG'),
('Kriek Mort Subite', '4.5', 'Fruitee', 'beers\\KriekMortSubite.PNG'),
('La Trappe Blonde', '6.5', 'Speciale Blonde', 'beers\\LaTrappeBlonde.PNG'),
('Leffe Blonde', '6.5', 'Abbaye', 'beers\\LeffeBlonde.PNG'),
('Leffe Brune', '6.5', 'Abbaye', 'beers\\LeffeBrune.PNG'),
('Leffe Royale', '7.5', 'Speciale Ambree', 'beers\\LeffeRoyale'),
('Leffe Royale Cascade Ipa', '7.5', 'Abbaye', 'beers\\LeffeRoyaleCascadeIPA.PNG'),
('Leffe Ruby', '5.0', 'Fruitee', 'beers\\LeffeRuby.PNG'),
('Lupulus', '7.5', 'Speciale Blonde', 'beers\\Lupulus.PNG'),
('Lindemans Kriek', '4.0', 'Fruitee', 'beers\\LindemansKriek.PNG'),
('Maes', '4.9', 'Pils', 'beers\\Maes.PNG'),
('Mystic Cerise', '3.5', 'Fruitee', 'beers\\MysticCerise.PNG'),
('Mystic White', '5.1', 'Blanche', 'beers\\MysticWhite.PNG'),
('Omer', '8.0', 'Speciale Blonde', 'beers\\Omer.PNG'),
('Orval', '6.2', 'Trappiste', 'beers\\Orval.PNG'),
('Peche Mel Bush', '8.5', 'Fruitee', 'beers\\PecheMelBush.PNG'),
('Primus', '5.2', 'Pils', 'beers\\Primus.PNG'),
('Rochefort 8', '9.2', 'Trappiste', 'beers\\Rochefort8.PNG'),
('Rochefort 10', '11.3', 'Trappiste', 'beers\\Rochefort10.PNG'),
('Sainte Nitouche Blondinette', '6.0', 'Speciale Blonde', 'beers\\SainteNitoucheBlondinette.PNG'),
('Stella Artois', '5.2', 'Pils', 'beers\\StellaArtois.PNG'),
('Surfine', '6.5', 'Saisons', 'beers\\Surfine.PNG'),
('Temps des Brunes', '6.0', 'Speciale Brune', 'beers\\TempsDesBrunes.PNG'),
('Timmermans Pêche', '5.0', 'Fruitee', 'beers\\TimmermansPeche.PNG'),
('Troubadour Magma', '9.0', 'Speciale Ambree', 'beers\\TroubadourMagma.PNG'),
('Triple Karmeliet', '8.0', 'Speciale Blonde', 'beers\\TripleKarmeliet.PNG'),
('Vedett', '6.0', 'Pils', 'beers\\Vedett.PNG'),
('Vedett Ipa', '6.0', 'IPA', 'beers\\VedettIPA.PNG'),
('Westmalle Triple', '9.5', 'Trappiste', 'beers\\WestmalleTriple.PNG');






